
# Enable vi mode
bindkey -v


# prompt style
if [ "$TERM_PROGRAM" != "Apple_Terminal" ]; then
  eval "$(oh-my-posh init zsh)"
fi

eval "$(oh-my-posh init zsh --config $HOME/my_dot_files/zsh/multiverse-neon.omp.json)"

# macOS
export HOMEBREW_NO_AUTO_UPDATE=1
## 可以使用ctrl+v / cat 来获取按键的信息
bindkey "^[[H" beginning-of-line # fn+left = home
bindkey "^[OH" beginning-of-line # fn+left = home
bindkey "^[[F" end-of-line # fn+right = end
bindkey "^[OF" end-of-line # fn+right = end
bindkey "^[[Z" reverse-menu-complete # shift-tab
bindkey "^[[1;3D" backward-word # option+left = 向前跳一个词
bindkey "^[[1;3C" forward-word # option+right = 向后跳一个词
bindkey "^P" up-line-or-search # ctrl+p
bindkey "^N" down-line-or-search # ctrl+n
